//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 12:41:31 PM IST 
//


package com.test.config.fts.callback.response.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AMLScanResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AMLScanResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AMLScanResponse" type="{http://devwbin01.nbf.ae/NBFAML.provider.ws:NBFAMLScan}amlScanResponseNew"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AMLScanResponse", propOrder = {
    "amlScanResponse"
})
@XmlRootElement(name = "AMLScanResponse", namespace = "NBFAMLScan")
public class AMLScanResponse {

    @XmlElement(name = "AMLScanResponse", required = true, nillable = true)
    protected AmlScanResponse2 amlScanResponse;

    /**
     * Gets the value of the amlScanResponse property.
     * 
     * @return
     *     possible object is
     *     {@link AmlScanResponseNew }
     *     
     */
    public AmlScanResponse2 getAMLScanResponse() {
        return amlScanResponse;
    }

    /**
     * Sets the value of the amlScanResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmlScanResponseNew }
     *     
     */
    public void setAMLScanResponse(AmlScanResponse2 value) {
        this.amlScanResponse = value;
    }

}
