//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 12:41:31 PM IST 
//


package com.test.config.fts.callback.response.stub;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AMLScanResponse_QNAME = new QName("http://devwbin01.nbf.ae/NBFAML.provider.ws:NBFAMLScan", "AMLScanResponse");

    /**
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AMLScanResponse }
     * 
     */
    public AMLScanResponse createAMLScanResponse() {
        return new AMLScanResponse();
    }

    /**
     * Create an instance of {@link AmlScanResponseNew }
     * 
     */
    public AmlScanResponse2 createAmlScanResponseNew() {
        return new AmlScanResponse2();
    }

    /**
     * Create an instance of {@link Response2 }
     * 
     */
    public Response2 createResponse2() {
        return new Response2();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AMLScanResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AMLScanResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://devwbin01.nbf.ae/NBFAML.provider.ws:NBFAMLScan", name = "AMLScanResponse")
    public JAXBElement<AMLScanResponse> createAMLScanResponse(AMLScanResponse value) {
        return new JAXBElement<AMLScanResponse>(_AMLScanResponse_QNAME, AMLScanResponse.class, null, value);
    }

}
