//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 12:41:31 PM IST 
//


package com.test.config.fts.callback.request.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AMLScan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AMLScan"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AMLScanRequest" type="{http://devwbin01.nbf.ae/NBFAML.provider.ws:NBFAMLScan}amlScanRequest"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AMLScan", propOrder = {
    "amlScanRequest"
})
@XmlRootElement(name = "AMLScan")
public class AMLScan {
	
    @XmlElement(name = "AMLScanRequest", required = true, nillable = true)
    protected AmlScanRequest amlScanRequest;

    /**
     * Gets the value of the amlScanRequest property.
     * 
     * @return
     *     possible object is
     *     {@link AmlScanRequest }
     *     
     */
    public AmlScanRequest getAMLScanRequest() {
        return amlScanRequest;
    }

    /**
     * Sets the value of the amlScanRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmlScanRequest }
     *     
     */
    public void setAMLScanRequest(AmlScanRequest value) {
        this.amlScanRequest = value;
    }

}
