//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 12:41:31 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://devwbin01.nbf.ae/NBFAML.provider.ws:NBFAMLScan")
package com.test.config.fts.callback.request.stub;
