//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.26 at 06:21:46 PM IST 
//


package com.test.config.uaefts.fts.callback.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FTSAML_UpdateAML_Output complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FTSAML_UpdateAML_Output"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{https://localhost/FTSAML/}UpdateAMLResponse" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FTSAML_UpdateAML_Output", propOrder = {
    "updateAMLResponse"
})
@XmlRootElement(name="UpdateAMLResponse", namespace="NBFAMLFTSCallback")
public class FTSAMLUpdateAMLOutput {

    @XmlElement(name = "UpdateAMLResponse", namespace = "https://localhost/FTSAML/")
    protected UpdateAMLResponse updateAMLResponse;

    /**
     * Gets the value of the updateAMLResponse property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateAMLResponse }
     *     
     */
    public UpdateAMLResponse getUpdateAMLResponse() {
        return updateAMLResponse;
    }

    /**
     * Sets the value of the updateAMLResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateAMLResponse }
     *     
     */
    public void setUpdateAMLResponse(UpdateAMLResponse value) {
        this.updateAMLResponse = value;
    }

}
