//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.26 at 06:21:46 PM IST 
//


package com.test.config.uaefts.fts.callback.stub;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UpdateAMLRequest_QNAME = new QName("https://localhost/FTSAML/", "UpdateAMLRequest");
    private final static QName _UpdateAMLResponse_QNAME = new QName("https://localhost/FTSAML/", "UpdateAMLResponse");
    private final static QName _FTSAMLUpdateAMLInput_QNAME = new QName("NBFAMLFTSCallback", "FTSAML_UpdateAML_Input");
    private final static QName _FTSAMLUpdateAMLOutput_QNAME = new QName("NBFAMLFTSCallback", "FTSAML_UpdateAML_Output");

    /**
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateAMLRequest }
     * 
     */
    public UpdateAMLRequest createUpdateAMLRequest() {
        return new UpdateAMLRequest();
    }

    /**
     * Create an instance of {@link UpdateAMLResponse }
     * 
     */
    public UpdateAMLResponse createUpdateAMLResponse() {
        return new UpdateAMLResponse();
    }

    /**
     * Create an instance of {@link CallbackInput }
     * 
     */
    public CallbackInput createFTSAMLUpdateAMLInput() {
        return new CallbackInput();
    }

    /**
     * Create an instance of {@link FTSAMLUpdateAMLOutput }
     * 
     */
    public FTSAMLUpdateAMLOutput createFTSAMLUpdateAMLOutput() {
        return new FTSAMLUpdateAMLOutput();
    }

    /**
     * Create an instance of {@link UpdateAMLRequestResponse }
     * 
     */
    public UpdateAMLRequestResponse createUpdateAMLRequestResponse() {
        return new UpdateAMLRequestResponse();
    }

    /**
     * Create an instance of {@link ObjAMLReq }
     * 
     */
    public ObjAMLReq createObjAMLReq() {
        return new ObjAMLReq();
    }

    /**
     * Create an instance of {@link UpdateAMLResponseResponse }
     * 
     */
    public UpdateAMLResponseResponse createUpdateAMLResponseResponse() {
        return new UpdateAMLResponseResponse();
    }

    /**
     * Create an instance of {@link UpdateAMLResponseResult }
     * 
     */
    public UpdateAMLResponseResult createUpdateAMLResponseResult() {
        return new UpdateAMLResponseResult();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateAMLRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateAMLRequest }{@code >}
     */
    @XmlElementDecl(namespace = "https://localhost/FTSAML/", name = "UpdateAMLRequest")
    public JAXBElement<UpdateAMLRequest> createUpdateAMLRequest(UpdateAMLRequest value) {
        return new JAXBElement<UpdateAMLRequest>(_UpdateAMLRequest_QNAME, UpdateAMLRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateAMLResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateAMLResponse }{@code >}
     */
    @XmlElementDecl(namespace = "https://localhost/FTSAML/", name = "UpdateAMLResponse")
    public JAXBElement<UpdateAMLResponse> createUpdateAMLResponse(UpdateAMLResponse value) {
        return new JAXBElement<UpdateAMLResponse>(_UpdateAMLResponse_QNAME, UpdateAMLResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CallbackInput }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CallbackInput }{@code >}
     */
    @XmlElementDecl(namespace = "NBFAMLFTSCallback", name = "FTSAML_UpdateAML_Input")
    public JAXBElement<CallbackInput> createFTSAMLUpdateAMLInput(CallbackInput value) {
        return new JAXBElement<CallbackInput>(_FTSAMLUpdateAMLInput_QNAME, CallbackInput.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FTSAMLUpdateAMLOutput }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FTSAMLUpdateAMLOutput }{@code >}
     */
    @XmlElementDecl(namespace = "NBFAMLFTSCallback", name = "FTSAML_UpdateAML_Output")
    public JAXBElement<FTSAMLUpdateAMLOutput> createFTSAMLUpdateAMLOutput(FTSAMLUpdateAMLOutput value) {
        return new JAXBElement<FTSAMLUpdateAMLOutput>(_FTSAMLUpdateAMLOutput_QNAME, FTSAMLUpdateAMLOutput.class, null, value);
    }

}
