//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.26 at 06:21:46 PM IST 
//


package com.test.config.uaefts.fts.callback.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpdateAMLResponseResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateAMLResponseResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UpdateAMLResponseResult" type="{NBFAMLFTSCallback}UpdateAMLResponseResult"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateAMLResponseResponse", propOrder = {
    "updateAMLResponseResult"
})
public class UpdateAMLResponseResponse {

    @XmlElement(name = "UpdateAMLResponseResult", required = true)
    protected UpdateAMLResponseResult updateAMLResponseResult;

    /**
     * Gets the value of the updateAMLResponseResult property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateAMLResponseResult }
     *     
     */
    public UpdateAMLResponseResult getUpdateAMLResponseResult() {
        return updateAMLResponseResult;
    }

    /**
     * Sets the value of the updateAMLResponseResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateAMLResponseResult }
     *     
     */
    public void setUpdateAMLResponseResult(UpdateAMLResponseResult value) {
        this.updateAMLResponseResult = value;
    }

}
