//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.26 at 06:21:46 PM IST 
//


package com.test.config.uaefts.fts.callback.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpdateAMLRequestResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateAMLRequestResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="objAMLReq" type="{NBFAMLFTSCallback}objAMLReq" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateAMLRequestResponse", propOrder = {
    "objAMLReq"
})
public class UpdateAMLRequestResponse {

    protected ObjAMLReq objAMLReq;

    /**
     * Gets the value of the objAMLReq property.
     * 
     * @return
     *     possible object is
     *     {@link ObjAMLReq }
     *     
     */
    public ObjAMLReq getObjAMLReq() {
        return objAMLReq;
    }

    /**
     * Sets the value of the objAMLReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjAMLReq }
     *     
     */
    public void setObjAMLReq(ObjAMLReq value) {
        this.objAMLReq = value;
    }

}
